# Generated by Django 5.2.7 on 2025-10-10 00:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_booking_return_date_booking_return_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='return_date',
            field=models.DateField(default=datetime.date(2025, 10, 10)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='return_time',
            field=models.TimeField(default=datetime.time(0, 10, 28, 154892)),
            preserve_default=False,
        ),
    ]
